{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.6"},"colab":{"provenance":[]}},"cells":[{"cell_type":"markdown","metadata":{"id":"QQM7oRc6eMui"},"source":["# Python para el análisis de datos -  UNAV 2020-2021\n","---\n","\n","# Manejo de errores y excepciones"]},{"cell_type":"markdown","metadata":{"id":"Zx1R1Fm7eMu-"},"source":["## Manejo de errores <a name=\"Manejo de errores\"></a> \n","[Volver al índice](#indice)"]},{"cell_type":"markdown","metadata":{"id":"4JTD7SzHeMu-"},"source":["En un programa podemos encontrarnos con distintos tipos de errores pero a grandes rasgos podemos decir que todos los errores pertenecen a una de las siguientes categorías.\n","\n","**Errores de sintaxis:** estos errores son seguramente los más simples de resolver, pues son detectados por el intérprete (o por el compilador, según el tipo de lenguaje que estemos utilizando) al procesar el código fuente y generalmente son consecuencia de equivocaciones al escribir el programa. En el caso de Python estos errores son indicados con un mensaje SyntaxError.\n","\n","**Errores de ejecución:** estos errores aparecen durante la ejecución del programa,su origen puede ser diverso y generalmente dependen de la parametrización concreta que se ha utilizado.\n","Es por ello que el resto de la unidad nos centraremos en cómo preparar nuestros programas para lidiar con este tipo de errores. Comunmente son llamados excepciones.\n","\n","Además, la sesión de debug hará que tengamos la capacidad total de detectarlos."]},{"cell_type":"markdown","metadata":{"id":"fJHwTDSYeOzz"},"source":["## Excepciones y Try-Catch <a name=\"Excepciones y Try-Catch\"></a> \n","[Volver al índice](#indice)"]},{"cell_type":"code","metadata":{"id":"q9YcFK3yeMu-","colab":{"base_uri":"https://localhost:8080/","height":200},"executionInfo":{"status":"error","timestamp":1666346425061,"user_tz":-120,"elapsed":210,"user":{"displayName":"Guillermo martín","userId":"05540387787462883316"}},"outputId":"d817003b-5db6-426b-8a44-5f8bf27a79a9"},"source":["dividendo = 5\n","divisor = 0\n","dividendo / divisor"],"execution_count":null,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-7-07751846ea33>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mdividendo\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mdivisor\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mdividendo\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mdivisor\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"markdown","metadata":{"id":"lbPK7GsjeMu-"},"source":["Para el manejo de excepciones los lenguajes proveen ciertas palabras reservadas, que nos permiten manejar las excepciones que puedan surgir y tomar acciones de recuperación para evitar la interrupción del programa o, al menos, para realizar algunas acciones adicionales antes de interrumpir el programa.\n","\n","En el caso de Python, el manejo de excepciones se hace mediante los bloques que utilizan las sentencias:\n","\n","- try: dentro del bloque try se ubica todo el código que pueda llegar a levantar una excepción, se utiliza el término levantar para referirse a la acción de generar una excepción.\n","\n","- except: en el bloque except se ubica el código que queremos que se realice cuando se lanza una excepción en el bloque try.\n","\n","\n"]},{"cell_type":"code","metadata":{"id":"F9Nbl125eMu-","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1636794093114,"user_tz":-60,"elapsed":273,"user":{"displayName":"Guillermo martín","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"05540387787462883316"}},"outputId":"52241873-18e2-4d0f-b2d9-de497ef517b7"},"source":["try:\n","    cociente = dividendo / divisor\n","except:\n","    print(\"No se permite la división por cero\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["No se permite la división por cero\n"]}]},{"cell_type":"markdown","metadata":{"id":"hDPIXHImeMu-"},"source":["Dado que dentro de un mismo bloque try pueden producirse excepciones de distinto tipo, es posible utilizar varios bloques except, cada uno para capturar un tipo distinto de excepción.\n","\n","Esto se hace especificando a continuación de la sentencia except el nombre de la excepción que se pretende capturar. Un mismo bloque except puede atrapar varios tipos de excepciones, lo cual se hace especificando los nombres de la excepciones separados por comas a continuación de la palabra except. Es importante destacar que si bien luego de un bloque try puede haber varios bloques except, se ejecutará, a lo sumo, uno de ellos."]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"GLWz0Y7vFSdz","executionInfo":{"status":"ok","timestamp":1666346435415,"user_tz":-120,"elapsed":194,"user":{"displayName":"Guillermo martín","userId":"05540387787462883316"}},"outputId":"f666312a-6dcf-4bd3-a9cf-aef17a930daa"},"source":["try:\n","    cociente = dividemdo / divisor\n","    archivo = open(\"miarchivo.txt\")\n","except ZeroDivisionError:\n","    print(\"No se permite la división por cero\")\n","except:\n","    print(\"cómo lanzar esto?\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["No se permite la división por cero\n"]}]},{"cell_type":"markdown","metadata":{"id":"VXeUh6FCmqIY"},"source":["## Finally <a name=\"Finally\"></a> \n","[Volver al índice](#indice)"]},{"cell_type":"markdown","metadata":{"id":"k9P4H8QoFOHF"},"source":["Puede ubicarse un bloque **finally** donde se escriben las sentencias de finalización, que son típicamente acciones de limpieza. La particularidad del bloque finally es que se ejecuta siempre, haya surgido una excepción o no. Es posible tener un bloque try sólo con finally, sin except."]},{"cell_type":"code","metadata":{"id":"HnsUGWR1eMu_","colab":{"base_uri":"https://localhost:8080/","height":373},"executionInfo":{"status":"error","timestamp":1666346633030,"user_tz":-120,"elapsed":210,"user":{"displayName":"Guillermo martín","userId":"05540387787462883316"}},"outputId":"525bc7aa-a16a-4fdc-f1f8-2814c4a9ed39"},"source":["def dividir(dividendo, divisor):\n","  try:\n","      cociente= 3\n","      cociente = dividendo / divisor\n","#      archivo = open(\"miarchivo.txt\")\n","      return cociente\n","  except ZeroDivisionError:\n","      print(\"No se permite la división por cero\")\n","  finally:\n","      print(\"Esto siempre se ejecuta\")\n","\n","  print(\"esto no te creas que siempre\")\n","\n","\n","a= dividir(7,0)\n","h= 5/a\n","\n","print(\"y esto se ejecuta?\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Esto siempre se ejecuta\n"]},{"output_type":"error","ename":"FileNotFoundError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-11-014c6a3d1e0e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0ma\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0mdividir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m7\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     16\u001b[0m \u001b[0mh\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     17\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m<ipython-input-11-014c6a3d1e0e>\u001b[0m in \u001b[0;36mdividir\u001b[0;34m(dividendo, divisor)\u001b[0m\n\u001b[1;32m      3\u001b[0m       \u001b[0mcociente\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0;36m3\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m#      cociente = dividendo / divisor\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m       \u001b[0marchivo\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"miarchivo.txt\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m       \u001b[0;32mreturn\u001b[0m \u001b[0mcociente\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'miarchivo.txt'"]}]},{"cell_type":"markdown","metadata":{"id":"nATaDTWjm6rB"},"source":["## Raise <a name=\"Raise\"></a> \n","[Volver al índice](#indice)"]},{"cell_type":"markdown","metadata":{"id":"DjpJfZ9WeMu_"},"source":["Cuando capturamos una excepción, es posible que después de realizar algún procesamiento particular del caso se quiera, la excepción se propague hacia la función que había invocado a la función actual. Para hacer esto Python nos brinda la instrucción raise.\n","\n","Si se invoca esta instrucción dentro de un bloque except, sin pasarle parámetros, Python levantará la excepción atrapada por ese bloque.\n","\n","También podría ocurrir que en lugar de propagar la excepción tal cual fue atrapada, quisiéramos lanzar una excepción distinta, más significativa para quien invocó a la función actual."]},{"cell_type":"code","metadata":{"id":"OUhiyJBLeMu_","colab":{"base_uri":"https://localhost:8080/","height":460},"executionInfo":{"status":"error","timestamp":1636795051091,"user_tz":-60,"elapsed":267,"user":{"displayName":"Guillermo martín","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"05540387787462883316"}},"outputId":"cd05d83c-5153-4337-86e2-8be656567101"},"source":["def dividir(dividendo, divisor):\n","  try:\n","      cociente = dividendo / divisor\n","#      archivo = open(\"miarchivo.txt\")\n","  except ZeroDivisionError:\n","      raise ZeroDivisionError(\"El divisor no puede ser cero vale?\")\n","  finally:\n","      print(\"Esto siempre se ejecuta\")\n","\n","  print(\"esto no te creas que siempre\")\n","  return cociente\n","\n","dividir(7,0)\n","print(\"y esto se ejecuta?\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Esto siempre se ejecuta\n"]},{"output_type":"error","ename":"ZeroDivisionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-17-25dac7da7643>\u001b[0m in \u001b[0;36mdividir\u001b[0;34m(dividendo, divisor)\u001b[0m\n\u001b[1;32m      2\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m       \u001b[0mcociente\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdividendo\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mdivisor\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;31m#      archivo = open(\"miarchivo.txt\")\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero","\nDuring handling of the above exception, another exception occurred:\n","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-17-25dac7da7643>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     11\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0mcociente\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 13\u001b[0;31m \u001b[0mdividir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m7\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     14\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"y esto se ejecuta?\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m<ipython-input-17-25dac7da7643>\u001b[0m in \u001b[0;36mdividir\u001b[0;34m(dividendo, divisor)\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m#      archivo = open(\"miarchivo.txt\")\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"El divisor no puede ser cero vale?\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m   \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m       \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Esto siempre se ejecuta\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: El divisor no puede ser cero vale?"]}]},{"cell_type":"markdown","metadata":{"id":"36r7by02pxJa"},"source":["## Acceso a la excepción <a name=\"Acceso a la excepción\"></a> \n","[Volver al índice](#indice)"]},{"cell_type":"markdown","metadata":{"id":"IBa4nOuReMu_"},"source":["Para acceder a la información de contexto estando dentro de un bloque except existen dos alternativas:\n","- Se puede utilizar la función exc_info del módulo sys. Esta función devuelve una tupla con información sobre la última excepción atrapada en un bloque except. Dicha tupla contiene tres elementos: el tipo de excepción, el valor de la excepción y las llamadas realizadas."]},{"cell_type":"code","metadata":{"id":"_ugYqllPeMu_","colab":{"base_uri":"https://localhost:8080/","height":435},"executionInfo":{"status":"error","timestamp":1636795134578,"user_tz":-60,"elapsed":253,"user":{"displayName":"Guillermo martín","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"05540387787462883316"}},"outputId":"be0ef267-b6ee-490e-c521-2526d4f9e6e5"},"source":["import sys\n","def dividir(dividendo, divisor):\n","  try:\n","      cociente = dividendo / divisor\n","#      archivo = open(\"miarchivo.txt\")\n","  except ZeroDivisionError:\n","\n","      print(\"0\", sys.exc_info()[0])\n","      print(\"1\", sys.exc_info()[1])\n","      print(\"2\", sys.exc_info()[2])\n","\n","  finally:\n","      print(\"Esto siempre se ejecuta\")\n","\n","  print(\"esto no te creas que siempre\")\n","  return cociente\n","\n","dividir(7,0)\n","print(\"y esto se ejecuta?\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["0 <class 'ZeroDivisionError'>\n","1 division by zero\n","2 <traceback object at 0x7fb00c390f50>\n","Esto siempre se ejecuta\n","esto no te creas que siempre\n"]},{"output_type":"error","ename":"UnboundLocalError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mUnboundLocalError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-20-aba1b41fe031>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     16\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0mcociente\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     17\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 18\u001b[0;31m \u001b[0mdividir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m7\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     19\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"y esto se ejecuta?\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m<ipython-input-20-aba1b41fe031>\u001b[0m in \u001b[0;36mdividir\u001b[0;34m(dividendo, divisor)\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m   \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"esto no te creas que siempre\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 16\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0mcociente\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     17\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     18\u001b[0m \u001b[0mdividir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m7\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mUnboundLocalError\u001b[0m: local variable 'cociente' referenced before assignment"]}]},{"cell_type":"markdown","metadata":{"id":"SHJVzjzWeMu_"},"source":["- Otra forma de obtener información sobre la excepción es utilizando la misma sentencia except, pasándole un identificador para que almacene una referencia a la excepción atrapada."]},{"cell_type":"code","metadata":{"id":"h8PtxhpWeMvA","colab":{"base_uri":"https://localhost:8080/","height":418},"executionInfo":{"status":"error","timestamp":1636795177981,"user_tz":-60,"elapsed":241,"user":{"displayName":"Guillermo martín","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"05540387787462883316"}},"outputId":"c53bfedb-2910-4503-d92b-4202994f704b"},"source":["def dividir(dividendo, divisor):\n","  try:\n","      cociente = dividendo / divisor\n","#      archivo = open(\"miarchivo.txt\")\n","\n","  except ZeroDivisionError as err:\n","      print(\"imprimir excepcion capturada\", err)\n","      print(\"imprimir excepcion capturada\", err.args)\n","\n","  finally:\n","      print(\"Esto siempre se ejecuta\")\n","\n","  print(\"esto no te creas que siempre\")\n","  return cociente\n","\n","dividir(7,0)\n","print(\"y esto se ejecuta?\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["imprimir excepcion capturada division by zero\n","imprimir excepcion capturada ('division by zero',)\n","Esto siempre se ejecuta\n","esto no te creas que siempre\n"]},{"output_type":"error","ename":"UnboundLocalError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mUnboundLocalError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-22-1575b387fd3d>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     14\u001b[0m   \u001b[0;32mreturn\u001b[0m \u001b[0mcociente\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 16\u001b[0;31m \u001b[0mdividir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m7\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     17\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"y esto se ejecuta?\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m<ipython-input-22-1575b387fd3d>\u001b[0m in \u001b[0;36mdividir\u001b[0;34m(dividendo, divisor)\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m   \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"esto no te creas que siempre\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 14\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0mcociente\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     15\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     16\u001b[0m \u001b[0mdividir\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m7\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mUnboundLocalError\u001b[0m: local variable 'cociente' referenced before assignment"]}]}]}